# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    versioning:
        enabled: true
        resolvers:
            query: false
            custom_header: false
            media_type: false
#    routing_loader: false
    view:
        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
